### ISSUE TITLE
 TypeError

### ISSUE THREAD

**Issue by AjinkyaKarode10** [superRaytin/paginationjs#76]
Cannot read property 'hooks' of undefined

 at Object.callHook (https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.3/pagination.js:631:27)
    at Object.initialize (https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.3/pagination.js:49:18)
    at w.fn.init.$.fn.(anonymous function) [as pagination] (https://cdnjs.cloudflare.com/ajax/libs/paginationjs/2.1.3/pagination.js:851:16)
    at http://localhost:8080/SpringCrudExample1/EmployeeController/show.htm:14:29

**Comment by superRaytin** [comment]
trace: https://github.com/superRaytin/paginationjs/issues/68#issuecomment-409867638
